### ISSUE TITLE
Upgrade eslint-plugin-import dependency

### ISSUE THREAD

**Issue by mwgamble** [nuxt/eslint-config#106]
Currently the eslint-plugin-import dependency is pinned at 2.19.1, which means we can't even upgrade it ourselves if we wanted to. It'd be great if this could (at the very least) be changed to ^2.19.1, so that it can be upgraded to a newer version that has important bugfixes.

**Comment by clarkdo** [comment]
v3.1.0 has been published with latest deps

**Comment by mwgamble** [comment]
Is there a reason why the dependency on `eslint-plugin-import` wasn't updated to use a `^` version lock?

**Comment by clarkdo** [comment]
Thanks, it was fixed because of a windows import/order bug in in 2.20.

The bug has been fixed, I've change it back to ^, thanks for the reminding.
