### ISSUE TITLE
The "parser" configuration option should be in the root of the .eslintrc.js file

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [nuxt/eslint-config#116]
I was going through the [eslint docs](https://eslint.org/docs/user-guide/configuring#specifying-parser) and it seems to imply that the `parser` key should be a root element in the `.eslintrc.js` file. Right now that key is a child of the the `parserOptions` key https://github.com/nuxt/create-nuxt-app/blob/8adf4ce7fcabcdf1952e81e650386f9a9a6ae1da/packages/cna-template/template/_.eslintrc.js#L9

**Comment by pi0** [comment]
I've moved issue to eslint-config to ensure about compat/performance side of using babel parser for eslint before closing. 

/cc @clarkdo @manniL @kevinmarrec

**Comment by SayakMukhopadhyay** [comment]
Thanks for linking to the docs. It clears things up.

**Comment by pi0** [comment]
Hi! I'm closing this issue since seems stalled. Please create a new one if still relevant 🙏🏼
