### ISSUE TITLE
Upgrade eslint-plugin-unicorn

### ISSUE THREAD

**Issue by Arslanoov** [nuxt/eslint-config#166]
Hello
Thank you for the library
Can you please upgrade eslint-plugin-unicorn? (this library uses 28.0.2, but the actual version is 34.0.1)

Because it cause issues with other libraries like this
EvgenyOrekhov/eslint-config-hardcore#318

**Comment by pi0** [comment]
Hi! Unicorn plugin updated in latest release :)
