### ISSUE TITLE
Conflicts on ESLint version with eslint-config-standard

### ISSUE THREAD

**Issue by fuegoio** [nuxt/eslint-config#199]
Hi everyone,

From the version 8.0.0, we got an issue that you can also see in the CI of this project, but yarn is not really verbose about it in contrary of npm:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: eslint-config-standard@16.0.3
npm WARN Found: eslint@8.11.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^8.11.0" from the root project
npm WARN   16 more (@nuxtjs/eslint-config, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^7.12.1" from eslint-config-standard@16.0.3
npm WARN node_modules/eslint-config-standard
npm WARN   eslint-config-standard@"^16.0.3" from @nuxtjs/eslint-config@9.0.0
npm WARN   node_modules/@nuxtjs/eslint-config
```

I think it is because the version of eslint-config-standard does not match the version 8 of ESLint. Has anyone got this issue ?

**Comment by iamandrewluca** [comment]
Temporary I installed version `eslint-config-standard@17`

```shell
npm i -D eslint-config-standard@next
```

**Comment by iamandrewluca** [comment]
For me it did work, I didn't have any problems installing it. 🤔

<img width="398" alt="image" src="https://user-images.githubusercontent.com/1881266/158197327-5d7cdb83-bfd2-4fb3-83d1-6ead9d47a8d4.png">

**Comment by fuegoio** [comment]
As you can see in this file https://github.com/nuxt/eslint-config/blob/master/packages/eslint-config/package.json, the version is pinned and npm is complaining on my side :/

**Comment by sebalaini** [comment]
I have the same problem with this package.json, I can't update anything related with eslint

```
  "dependencies": {
    "@nuxt/babel-preset-app": "^2.15.8",
    "core-js": "^3.22.2",
    "nuxt": "^2.15.8",
    "vue-flux": "^6.4.0"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^6.0.1",
    "@nuxtjs/eslint-module": "^3.1.0",
    "@nuxtjs/style-resources": "^1.2.1",
    "babel-core": "7.0.0-bridge.0",
    "eslint": "^7.32.0",
    "eslint-plugin-nuxt": "^3.2.0",
    "sass": "^1.51.0",
    "sass-loader": "10.2.1",
    "style-loader": "^2.0.0",
    "stylelint": "^13.13.1",
    "stylelint-config-standard": "^22.0.0",
    "stylelint-declaration-use-variable": "^1.7.3",
    "webpack": "4.46.0"
  }
```

**Comment by pi0** [comment]
Hi. Would you please check against v10 with a clean lockfile if issue still happens to reopen this issue?
