### ISSUE TITLE
Disable multiword-rule for error.vue

### ISSUE THREAD

**Issue by olivervorasai** [nuxt/eslint-config#201]
Nuxt 3 added support for `error.vue` in the source directory. https://v3.nuxtjs.org/docs/usage/error-handling#rendering-an-error-page

This is caught by ESLint:
![image](https://user-images.githubusercontent.com/6283219/158844778-37ff877b-dbf7-4773-850c-0955c23c00c3.png)

I think this file should be ignored in the same manner in which `app.vue` is not caught by this rule.

Another possible solution would be to add this specific file to the rule overrides as done in https://github.com/nuxt/eslint-config/pull/190 (although this assumes that error.vue never changes from this point forward).

**Comment by danielroe** [comment]
Yes, I agree with @olivervorasai 👍
