### ISSUE TITLE
Nuxt 3: `plugin:vue/vue3-recommended` instead of `plugin:vue/recommended`

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/eslint-config#216]
Is this the right package to use with ESLint for Nuxt 3 development? I keep seeing Vue 2-related errors which are most likely due to the following rule `plugin:vue/recommended`.

**Comment by junepark202012** [comment]
I'm also getting Vue 2 Specific errors.

**Comment by thijsw** [comment]
> Indeed, for example: `vue/no-multiple-template-root`

And `vue/no-v-model-argument`

**Comment by StefanGhiban** [comment]
Hi! I am still seeing vue 2 specific errors...

**Comment by robsonsobral** [comment]
> Indeed, for example: `vue/no-multiple-template-root`

@rikzwarthoff , that a look at https://github.com/nuxt/eslint-config/issues/292#issuecomment-1669069218
