### ISSUE TITLE
ESLint config revamp

### ISSUE THREAD

**Issue by pi0** [nuxt/eslint-config#240]
We initially made `@nuxtjs/eslint-config` configuration (back in 2018 by @manniL) mainly for the purpose of internal usage for [nuxt/nuxt.js](https://github.com/nuxt/nuxt.js) usage and also consistency with ecosystem modules with the same styles. Later, a superset of `@nuxtjs/eslint-config-typescript` was made to cover typescript usage

Since then this nice configuration has also been adopted by many Nuxt users, but I also personally even used the typescript variant for non-nuxt js projects! 

After an initial internal discussion with @danielroe and @Atinux, I think it is time we revamp configurations in mono-repo by adding two new packages:

## `@nuxt/eslint-config`

A shared public configuration that we recommend to Nuxt users to use for their Nuxt projects. It should not include any style-related rules and extend vue recommended preset + [nuxt plugin](https://github.com/nuxt/eslint-config) (needs update? /cc @clarkdo) with typescript support out of the box.

## `@nuxt/eslint-config-internal`

Extending public configuration and including rules such as unicorn rules and no-console are important for internal and module authors. It shall also set basic code styles (I'm happy with the current standard-js style). At the same time, I would like to consider supporting prettier compatibility and recommend it (#224) (with custom config no-semi, single-qoute) 

## Current monorepo packages

We shall keep maintaining them until adoption happens

**Comment by antfu** [comment]
Sounds good to me!

A bit nitpicking is I found the name `@nuxt/eslint-config-internal` a bit confusing. `internal` sounds like a subset of the default one instead of a superset (feels it's describing its own property rather than its target usage). Maybe `@nuxt/eslint-config-tooling` or `@nuxt/eslint-config-module`?

**Comment by pi0** [comment]
Would `@nuxt/eslint-config-nuxt` be too confusing? (considering will be consumed by framework, ad-hoc modules and modules)

**Comment by harlan-zw** [comment]
Hmm as a module author I don't really like prettier but obviously want to keep consistent with the ecosystem. 

Maybe there could be a less opinionated internal config? I'll probably just keep using `@antfu/eslint-config` on top of whatever the nuxt eslint recommendation is :eyes:

**Comment by danielroe** [comment]
Closing to track in https://github.com/nuxt/eslint-config/issues/303.
