### ISSUE TITLE
Clarify README

### ISSUE THREAD

**Issue by rudolfbyker** [nuxt/eslint-config#288]
The README does not currently explain the difference between `@nuxt/eslint-config` and `@nuxtjs/eslint-config`.

**Comment by fahmifitu** [comment]
I agree. the current README file is highly misleading and causes confusion.

The README fails to provide clear guidance on which config section is applicable to each Nuxt.js version. The config section is vaguely named "opinionated/non-opinionated" without any accompanying description, making it difficult for users to determine the appropriate section for their needs. Furthermore, the second section lacks clarity regarding the version it is intended for.

Inconsistent installation instructions: In the second section, the installation instructions suggest executing npm i -D @nuxtjs/eslint-config. However, in the config section, it states that the package to be added is @nuxt/eslint-config. 

Also, How does this package correlate with nuxt/eslint-plugin-nuxt & nuxt/eslint-module?

Eveything about nuxt seems straightforward except for this module.

**Comment by Mallfurion** [comment]
I agree that there is a great confusion when trying to setup Linting and Formatting for a Nuxt 3 Project.
Especially if that project uses TypeScript, I cannot be sure which setup I should use for all my new projects.

I can see that the Code Style documentation page was updated recently, but the README file still mentions repositories from @nuxtjs when using TypeScript. 

Along side this confusion, there is also the eslint-config setup from @antfu which takes a different approach, whilst also providing a form of formatting. It also has much recent commits and package versions (2 days ago a time of writing).

I do believe that it would be a real helper for all of us in the community if this confusion was resolved, or at least an oficial response would be given.

@danielroe @Atinux
