### ISSUE TITLE
Whitelisting auto-imported function

### ISSUE THREAD

**Issue by OysterD3** [nuxt/eslint-config#304]
Currently, it doesn't have any whitelisted function for eslint.
It will be caused eslint to give `no-undef` error warning when we are using `eslint:recommended`

We can just follow the way that https://github.com/antfu/unplugin-auto-import did

**Comment by ColtHands** [comment]
+ to this

**Comment by Revadike** [comment]
Dupe of https://github.com/nuxt/eslint-config/issues/309
