### ISSUE TITLE
Eslint with Nuxt3 auto-import

### ISSUE THREAD

**Issue by fishfitz** [nuxt/eslint-config#309]
Seems very basic but I can't find anywhere an eslint setup that works with Nuxt3 auto-import, to avoid no-undef errors. I'm not using typescript.

I tried this package and following: @antfu/eslint-config, plugin:nuxt/recommended, @nuxtjs/eslint-config, @nuxt/eslint-config-typescript, with no luck so far.

The only thing that works for now is setting each reference in .eslintrc globals...

Could someone consider providing a working example? Here is a link to a Stackoverflow bounty related to this question: https://stackoverflow.com/questions/76803864/eslint-with-nuxt3-auto-import

**Comment by MarioAda** [comment]
Same problem here.

**Comment by RihanArfan** [comment]
The steps are on README.md but make sure you don't follow anything below the "@nuxtjs/eslint-config and @nuxtjs/eslint-config-typescript" section as that's for Nuxt 2, and instead only follow the first section.

https://github.com/nuxt/eslint-config?tab=readme-ov-file#nuxteslint-config

**Comment by OysterD3** [comment]
You can try this out: https://gist.github.com/OysterD3/41e82e293aa46e9f0dcffa04b3dedf86

**Comment by cco3** [comment]
How does this fix the issue?  Using `@nuxt/eslint-config` on a nuxt3 project doesn't recognize my auto-imports...I still have to register those values as globals.

**Comment by cco3** [comment]
Same issue is open over here:
https://github.com/nuxt/eslint-config/issues/321

**Comment by m-shum** [comment]
> Using `@nuxt/eslint-config` it works for me, wasnt working with `@nuxtjs/...`

Would you mind sharing your config? I'm using the same plugin but still getting this issue. It's the recommended eslint config everywhere but I've genuinely had fewer issues setting up all the plugins & configs manually.

**Comment by OysterD3** [comment]
> https://gist.github.com/OysterD3/41e82e293aa46e9f0dcffa04b3dedf86

Try this: https://gist.github.com/OysterD3/41e82e293aa46e9f0dcffa04b3dedf86

**Comment by OysterD3** [comment]
> > Using `@nuxt/eslint-config` it works for me, wasnt working with `@nuxtjs/...`
> 
> Would you mind sharing your config? I'm using the same plugin but still getting this issue. It's the recommended eslint config everywhere but I've genuinely had fewer issues setting up all the plugins & configs manually.

Try this

```typescript
import { defineNuxtModule } from '@nuxt/kit';
import { promises as fs } from 'node:fs';

export default defineNuxtModule({
  setup(opts, nuxt) {
    nuxt.hook('imports:context', async (ctx) => {
      const imports = await ctx
        .getImports()
        .then((r) => r.filter((i) => !i.type));
      const eslintConfigs = { globals: {} };
      imports
        .map((i) => i.as ?? i.name)
        .filter(Boolean)
        .sort()
        .forEach((name) => {
          eslintConfigs.globals[name] = true;
        });
      const jsonBody = JSON.stringify(eslintConfigs, null, 2);
      await fs.writeFile('.eslintrc.json', jsonBody);
    });
  },
});
```

**Comment by m-shum** [comment]
Still having this issue after updating this package. Autoimports of utils and composables are not recognised outside of component files (for example, utils used in composable files will throw an error unless imported)

**Comment by denbon05** [comment]
If you are using TypeScript, perhaps we could disable the rule in the `eslint.config.js` and let TS handle undefined variables in the project

```js
"no-undef": "off", // let TS handle undefined variables
```
