### ISSUE TITLE
Remove reference to `@nuxtjs/eslint-config` from the README

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/eslint-config#311]
It is not clear that `@nuxt/eslint-config` is for Nuxt 3 while `@nuxtjs/eslint-config` is for Nuxt 2.
Either make it clear in the README or remove reference to `@nuxtjs/eslint-config` as it can cause confusion.
I accidentally installed the wrong one in my Nuxt 3 project.

**Comment by RihanArfan** [comment]
#309 is a perfect example of people getting confused. I too also did before.

**Comment by mubaidr** [comment]
Yes, please. Since `@nuxt/eslint-config` supports typescript by default, the section `[TypeScript](https://github.com/nuxt/eslint-config#typescript)` makes this even more confusing for new comers.
