### ISSUE TITLE
nuxt and airbnb code style

### ISSUE THREAD

**Issue by dementor5** [nuxt/eslint-config#41]
How can i use nuxt.js with airbnb code style?
https://www.npmjs.com/package/eslint-config-airbnb-base

There is a conflict with eslint-config-airbnb-base and @nuxtjs/eslint-config.
Because It has a standard js code style as dependencies.

It's would be nice to make separate nuxt-eslint-config package without hard coded standard code style.

This is my .eslintrc.js:
```
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true,
  },
  parserOptions: {
    parser: 'babel-eslint',
  },
  extends: [
    '@nuxtjs',
    'airbnb-base',
    'plugin:nuxt/recommended',
  ],
  // add your custom rules here
  rules: {
    // from https://github.com/nuxt/eslint-config/blob/master/index.js
    'import/no-unresolved': 0,
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0,
    'no-console': process.env.NODE_ENV === 'production' ? 2 : 0,
  },
  settings: {
    'import/core-modules': [
      // for disable "'vue' should be listed in the project's dependencies" error
      'vue',
    ],
  },
};
```
and this is my devDependencies from package.json:
```
  "devDependencies": {
    "@nuxtjs/eslint-config": "^0.0.1",
    "@vue/test-utils": "^1.0.0-beta.27",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^24.1.0",
    "eslint": "^5.15.1",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-config-standard": ">=12.0.0",
    "eslint-loader": "^2.1.2",
    "eslint-plugin-import": ">=2.16.0",
    "eslint-plugin-jest": ">=22.3.0",
    "eslint-plugin-node": ">=8.0.1",
    "eslint-plugin-nuxt": ">=0.4.2",
    "eslint-plugin-promise": ">=4.0.1",
    "eslint-plugin-standard": ">=4.0.0",
    "eslint-plugin-vue": "^5.2.2",
    "jest": "^24.1.0",
    "nodemon": "^1.18.9",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "vue-jest": "^3.0.3"
  }
```

**Comment by manniL** [comment]
Hey @dementor5 	

It'd be the easiest to copy the rules over which you like/need from the nuxt-eslint config. We will stick to standard style and will likely not release an airbnb version. This doesn't mean it's bad or "unwanted" but that we focus on one style in all the nuxt projects. 

Feel free to adapt as you like 👍

**Comment by dementor5** [comment]
Create airbnb specified version - not is my idea.
My idea - to create separate nuxt-eslint-config without preferred code style, only nuxt and vue specifics rules set.
Then In own project i can select my preferred base code standard and extend it by nuxt/vue specifics.

**Comment by manniL** [comment]
That makes sense, but would still mean that we have to support multiple versions as we use `standard-style` in all nuxt-related projects and want to provide a decent default linting (also with regards to an uniform code style)

**Comment by dementor5** [comment]
Just remove eslint-config-standard and eslint-plugin-standard from dependencies of nuxt-eslint-config and add it in nuxt root package.json

**Comment by dementor5** [comment]
I see it like this: just move eslint-config-standard and eslint-plugin-standard dependencies fromhttps://github.com/nuxt/eslint-config/blob/master/package.json to https://github.com/nuxt/eslint-config/blob/master/package.json

**Comment by manniL** [comment]
Definitely thanks for bringing it up! ☺️

**Comment by tettoffensive** [comment]
@utrumo What did you end up doing for this?

I was using `airbnb-base` for a project based on vue-cli that I'm now converting to nuxt. But `@nuxtjs/eslint-config` isn't playing nicely with it - even if I switch my extends in `.eslintrc.js` it still is switching the style to nuxt's preferred. I don't really want to change coding styles in a middle of a project.

**Comment by cwenzelg** [comment]
I have the same issue and would like to have an easy way to use my one style.

**Comment by ahsandev2019** [comment]
still no airbnb version ?

**Comment by markabruce** [comment]
Hi guys, 

I know this is pretty old, but I've managed to get AirBnb ESLint working with some simple steps and have posted it on [Medium](https://medium.com/@markabrucey/configuring-nuxtjs-to-use-airbnb-eslint-with-vuetify-d56eedf14f3a):

If I'm not allowed to post this, please accept my apology and remove the comment, though it was at the top of the google search when attempting to figure this out and I think others may find it helpful too.
