### ISSUE TITLE
Non-null assertion

### ISSUE THREAD

**Issue by filipigustavo** [nuxt/eslint-config#64]
Hi, I have a nuxt+typescript project and I'm getting this error:

> error  Parsing error: Unexpected token
> 4 | @Component
  5 | class ProductComponent extends Vue {
> 6 |   @Prop(Object) product!: Object
   __ | ________________________^
  7 | }
  8 |
  9 | export default ProductComponent

-------------------
my tsconfig.json:
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": [
      "esnext",
      "esnext.asynciterable",
      "dom"
    ],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "./*"
      ],
      "@/*": [
        "./*"
      ]
    },
    "types": [
      "@types/node",
      "@nuxt/types"
    ],
    "experimentalDecorators": true,
    "resolveJsonModule": true
  },
  "exclude": [
    "node_modules"
  ]
}

-------------------
my .eslintrc.js:
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: [
    '@nuxtjs',
    'plugin:nuxt/recommended',
    '@nuxtjs/eslint-config-typescript'
  ],
  // add your custom rules here
  rules: {
    "no-console": "off"
  }
}

-------------------
my package.json has these packages:
"dependencies": {
    "@nuxtjs/axios": "^5.6.0",
    "@nuxtjs/pwa": "^3.0.0-0",
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "^2.0.1",
    "nuxt": "^2.9.2",
    "nuxt-property-decorator": "^2.4.0"
  },
  "devDependencies": {
    "@nuxt/typescript-build": "^0.2.8",
    "@nuxtjs/eslint-config": "^1.1.2",
    "@nuxtjs/eslint-config-typescript": "^0.1.3",
    "@nuxtjs/eslint-module": "^1.1.0",
    "babel-eslint": "^10.0.3",
    "eslint": "^6.4.0",
    "eslint-plugin-nuxt": ">=0.4.3",
    "vuex-module-decorators": "^0.10.1"
  }

I can't use the non-null assertion. How can I fix this problem?
This configuration was made following the instructions in https://typescript.nuxtjs.org

Thanks.

**Comment by b-barry** [comment]
Getting same issue on a fresh nuxt+ typescript project

**Comment by b-barry** [comment]
Getting the same issue with a fresh nuxt + typescript setup

**Comment by ShaneXie** [comment]
save error, super annoying !

**Comment by ShaneXie** [comment]
finally found the reason, simply remove 
```js
parserOptions: {
  parser: 'babel-eslint'
}
```
in the `.eslintrc.js`  
the reason is this parser is conflict with the parser used in this package.

**Comment by filipigustavo** [comment]
> finally found the reason, simply remove
> 
> ```js
> parserOptions: {
>   parser: 'babel-eslint'
> }
> ```
> 
> in the `.eslintrc.js`
> the reason is this parser is conflict with the parser used in this package.

Great, it's worked for me. Thanks.

**Comment by kevinmarrec** [comment]
**@nuxtjs/eslint-config-typescript** set a TypeScript parser, so you need to not override it. (i.e. https://github.com/nuxt/eslint-config/issues/64#issuecomment-533512278). Thanks @axe-me
