### ISSUE TITLE
eslint 6 compatibility

### ISSUE THREAD

**Issue by fengerzh** [nuxt/eslint-config#69]
Hi, there,

eslint-plugin-vue 6.0.0 just released, solved the incompatible issue with eslint 6.0. Could you please also upgrade? Thanks!

**Comment by ThibaultVlacich** [comment]
Every other Nuxt ESLint-related packages have been updated, this is the last one required to be able to finally have compatibility with ESLint 6, more than 5 months after ESLint 6 release.

**Comment by clarkdo** [comment]
@nuxtjs/eslint-config 2.0 has been published with eslint 6
