### ISSUE TITLE
Unmet peer dependency "typescript" with version 2.0.0

### ISSUE THREAD

**Issue by ThibaultVlacich** [nuxt/eslint-config#71]
I'm using the `@nuxtjs/eslint-config` package for my Nuxt application, and with the 2.0 version I'm getting this warning now:

> warning "@nuxtjs/eslint-config > eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".

Which is weird since this is not the typescript version of the config.

**Comment by ThibaultVlacich** [comment]
@clarkdo Any idea?

**Comment by clarkdo** [comment]
cc @kevinmarrec

**Comment by clarkdo** [comment]
From the dependency tree, it looks like the dependency is from eslint-plugin-jest

**Comment by kevinmarrec** [comment]
@clarkdo Indeed, and well it's a dependency warning, this isn't the only one showing up when installing nuxt deps for the first time AFAIK (or at least some community modules)

**Comment by clarkdo** [comment]
Related issue https://github.com/jest-community/eslint-plugin-jest/issues/467

**Comment by ThibaultVlacich** [comment]
I'm using Yarn. Looks like this as not been implemented yet as the proposal is still in the "accepted" state. https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md

Thanks for the explanation. I'm closing :)

**Comment by clarkdo** [comment]
From change log, yarn has implemented it since 1.13 https://github.com/yarnpkg/yarn/blob/master/CHANGELOG.md#1130
