### ISSUE TITLE
Should use vue/script-indent

### ISSUE THREAD

**Issue by gotenxds** [nuxt/eslint-config#76]
When using typescript eslint for some reason the indent rules are wrong and look as such:

```ts
<script>
import x from y;
import z from o;

  @Component()
export default class foo extends Vue {
  private bar: Bar;
}
</script>
```

Using the vue script indent rule fixes it, like so:

```ts
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  extends: [
    '@nuxtjs/eslint-config-typescript',
  ],
  rules: {
    indent: "off",
    'vue/script-indent': ['error', 2, {
      baseIndent: 1
    }]
  }
}
```

**Comment by kevinmarrec** [comment]
@gotenxds Is it because you were missing `lang="ts"` in `script` ?

Is it reproducible in a `.ts` file instead of `.vue` one ?

**Comment by davelsan** [comment]
Hi,

I agree with @gotenxds, I think we should use `vue/script-indent`.

While I cannot exactly comment on the class-component syntax issue he is having, with `vue-composition-api` the base ESLint `indent` rule causes the following error to pop-up on VSCode.

> Cannot read property 'loc' of undefined

The error goes away after switching off the base `indent` rule and enabling `vue/script-indent`.

> Is it reproducible in a `.ts` file instead of `.vue` one ?

Shouldn't `*.ts` files use the `@typescript-eslint/indent` rule?

 I ran into this same problem while linting regular *.ts files in a Node.js project. See typescript-eslint/typescript-eslint#792, specifically [this](https://github.com/typescript-eslint/typescript-eslint/issues/792#issuecomment-517762395) comment, for more information.
